export default defineNuxtConfig({
  devtools: { enabled: false },
  modules: ['@nuxtjs/tailwindcss'],
  ssr: true,
  app: {
    baseURL: '/',
    head: {
      htmlAttrs: { lang: 'it' },
      title: 'Implantologia Smiledoc - Dott. Piernatale Civero | Monterotondo',
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        { name: 'description', content: 'Impianti dentali a Monterotondo e dintorni. Il Dott. Piernatale Civero e il team Smiledoc ti aiutano a tornare a sorridere con impianti fissi, anche in 24 ore. Prenota una visita.' },
        { name: 'theme-color', content: '#1e3a5f' },
        { name: 'robots', content: 'index, follow' },
        { name: 'author', content: 'Dott. Piernatale Civero - Centro Odontoiatrico Smiledoc' },
        { name: 'geo.region', content: 'IT-RM' },
        { name: 'geo.placename', content: 'Monterotondo' },
        { name: 'geo.position', content: '42.0531;12.6209' },
        { name: 'ICBM', content: '42.0531, 12.6209' },
        { property: 'og:locale', content: 'it_IT' },
        { property: 'og:type', content: 'website' },
        { property: 'og:site_name', content: 'Implantologia Smiledoc' },
        { property: 'og:title', content: 'Implantologia Smiledoc - Dott. Piernatale Civero | Monterotondo' },
        { property: 'og:description', content: 'Impianti dentali a Monterotondo. Denti fissi in 24 ore con il Dott. Civero. 25+ anni di esperienza, 5000+ impianti. Garanzia 10 anni.' },
        { property: 'og:url', content: 'https://implantologiasmiledoc.it' },
        { property: 'og:image', content: 'https://implantologiasmiledoc.it/img/og-image.png' },
        { property: 'og:image:width', content: '1200' },
        { property: 'og:image:height', content: '630' },
        { name: 'twitter:card', content: 'summary_large_image' },
        { name: 'twitter:title', content: 'Implantologia Smiledoc - Dott. Piernatale Civero' },
        { name: 'twitter:description', content: 'Impianti dentali a Monterotondo. Denti fissi in 24 ore. Garanzia 10 anni.' },
        { name: 'twitter:image', content: 'https://implantologiasmiledoc.it/img/og-image.png' },
      ],
      link: [
        { rel: 'canonical', href: 'https://implantologiasmiledoc.it' },
        { rel: 'stylesheet', href: 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css' },
        { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
        { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' },
        { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap' },
        { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
        { rel: 'apple-touch-icon', sizes: '180x180', href: '/img/apple-touch-icon.png' },
      ],
    },
  },
  routeRules: {
    '/': { prerender: true },
    '/blog': { prerender: true },
    '/blog/**': { prerender: true },
    '/grazie': { prerender: true },
  },
  nitro: {
    prerender: {
      routes: ['/'],
    },
  },
  compatibilityDate: '2024-01-01',
})
